version: 2.0
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
         name: Start docker
         command: |
          mkdir -p ./volumes/mattermost/{data,logs,config,plugins}
          sudo chown -R 2000:2000 ./volumes/mattermost/
          docker-compose up
     - run:
         name: Tests
         command: |
           cd node
           npm run test